# Do Componente 7 - Fortalecimento Jurídico e Institucional para a Gestão da Biodiversidade.

::: {.callout-note icon=false appearance="simple"}

**Objetivo Geral: Promover meios e condições para o fortalecimento da infra-estrutura de pesquisa e gestão, para o acesso à tecnologia e transferência de tecnologia, para a formação e fixação de recursos humanos, para mecanismos de financiamento, para a cooperação internacional e para a adequação jurídica visando à gestão da biodiversidade e à integração e à harmonização de políticas setoriais pertinentes à biodiversidade.**

:::

## 16.1 Primeira diretriz: Fortalecimento da infra-estrutura de pesquisa e gestão da biodiversidade. Fortalecimento e ampliação da infra-estrutura das instituições brasileiras, públicas e privadas, envolvidas com o conhecimento e com a gestão da biodiversidade.

16.1.1 Recuperar a capacidade dos órgãos do Sistema Nacional do Meio Ambiente - SISNAMA para executar sua missão em relação ao licenciamento e à fiscalização da biodiversidade.

16.1.2 Aprimorar a definição das competências dos diversos órgãos de governo de forma a prevenir eventuais conflitos de competência quando da aplicação da legislação ambiental pertinente à biodiversidade.

16.1.3 Fortalecer o conjunto de unidades de conservação e sua integração no SISNAMA.

16.1.4 Estimular iniciativas para a criação de bases de pesquisa de campo permanente em unidades de conservação de proteção integral em cada um dos biomas brasileiros.

16.1.5 Promover o fortalecimento da infra-estrutura e a modernização das instituições brasileiras envolvidas com o inventário e a caracterização da biodiversidade, tais como coleções zoológicas, botânicas e de microrganismos, bancos de germoplasma e núcleos de criação animal.

16.1.6 Fortalecer instituições científicas com programas de pesquisa, criando, quando necessário, centros específicos em cada um dos biomas visando a fortalecer a pesquisa sobre recursos biológicos e suas aplicações.

16.1.7 Adequar a infra-estrutura das instituições que trabalham com recursos genéticos, componentes do patrimônio genético e conhecimentos tradicionais para conservar de forma segura, a curto, a médio e em longo prazo, espécies de interesse socioeconômico e as culturas de povos indígenas, quilombolas e outras comunidades locais do país.

16.1.8 Apoiar programas de pesquisa e de infra-estrutura voltados para o conhecimento tradicional de povos indígenas, quilombolas e outras comunidades locais, com a participação destes.

16.1.9 Apoiar a participação efetiva de especialistas das diferentes regiões do país em programas de seqüenciamento genético e outros programas para o desenvolvimento de tecnologias a partir da utilização de recursos biológicos.

16.1.10 Formalizar e fortalecer centros de referência depositários de organismos associados a produtos e processos patenteados no Brasil.

16.1.11 Promover a integração de programas e ações da esfera federal, das estaduais e das municipais e da sociedade civil organizada, relacionados à pesquisa, à formação de recursos humanos, a programas e projetos em áreas relacionadas à biodiversidade.

16.1.12 Incentivar a formação e consolidação de redes nacionais de pesquisa, desenvolvimento tecnológico e gestão da biodiversidade, como forma de promover e facilitar o intercâmbio sobre biodiversidade entre diferentes setores da sociedade.

16.1.13 Criar estímulos à gestão da biodiversidade, tais como prêmios a pesquisas e projetos de conservação e utilização sustentável.

16.1.14 Criar estímulos para organizações não-governamentais que atuam na proteção da biodiversidade.

16.1.15 Apoiar a criação de centros de documentação especializados para cada um dos biomas brasileiros para facilitar a cooperação científica dentro e fora do país.

16.1.16 Estimular o desenvolvimento de programa de apoio a publicações científicas sobre a biodiversidade brasileira, particularmente guias de campo, chaves taxonômicas, catalogação eletrônica de floras e faunas, revisões sistemáticas, monografias e estudos etnobiológicos.

## 16.2 Segunda diretriz: Formação e fixação de recursos humanos. Promoção de programas de formação, atualização e fixação de recursos humanos, inclusive a capacitação de povos indígenas, quilombolas e outras comunidades locais, para a ampliação e o domínio dos conhecimentos e das tecnologias necessárias à gestão da biodiversidade.

16.2.1 Instituir programas de formação, atualização e fixação de recursos humanos em instituições voltadas para o inventário, a caracterização, a classificação e a gestão da biodiversidade dos diversos biomas do país.

16.2.2 Reduzir as disparidades regionais, estimulando a capacitação humana e institucional em gestão da biodiversidade, inclusive em biotecnologia, promovendo a criação de mecanismos diferenciados para a contratação imediata nas instituições de ensino e pesquisa em regiões carentes e realizando a fixação de profissionais envolvidos com a capacitação em pesquisa e gestão da biodiversidade.

16.2.3 Fortalecer a pós-graduação ou os programas de doutorado em instituições de pesquisa nos temas relacionados aos objetivos da Convenção sobre Diversidade Biológica.

16.2.4 Apoiar a capacitação e a atualização de povos indígenas, quilombolas e outras comunidades locais quanto à gestão da biodiversidade, especialmente para agregação de valor e comercialização de produtos da biodiversidade derivados de técnicas tradicionais sustentáveis.

16.2.5 Apoiar formação ou aperfeiçoamento em gestão da biodiversidade de técnicos que atuem em projetos ou empreendimentos com potencial impacto ambiental.

16.2.6 Apoiar iniciativas de ensino a distância em áreas relacionadas à biodiversidade.

16.2.7 Promover a ampla divulgação dos termos da legislação de acesso aos recursos genéticos, aos componentes do patrimônio genético e aos conhecimentos tradicionais associados junto aos setores relacionados a esta temática.

16.2.8 Promover cursos e treinamentos para servidores públicos, inclusive juízes, membros do Ministério Público, polícia federal, civil e militar nos campos de gestão e proteção da biodiversidade.

16.2.9 Promover e apoiar a formação de recursos humanos voltados para o desenvolvimento e a disseminação de redes de informação sobre biodiversidade.

16.2.10 Capacitar pessoal para a gestão da biodiversidade em unidades de conservação.

16.2.11 Promover eventos regionais para os povos indígenas, quilombolas e outras comunidades locais com o objetivo de divulgar e esclarecer os termos da legislação de acesso a recursos genéticos, e capacitar agentes locais.

16.2.12 Estimular a cooperação entre governo, universidades, centros de pesquisa, setor privado e organizações da sociedade civil na elaboração de modelos de gestão da biodiversidade.

16.2.13 Apoiar a cooperação entre o setor público e o privado para formação e fixação de recursos humanos voltados para o desempenho de atividades de pesquisa em gestão da biodiversidade, especialmente no que tange à utilização de recursos biológicos, manutenção e utilização dos bancos de germoplasma.

## 16.3 Terceira diretriz: Acesso à tecnologia e transferência de tecnologia. Promoção do acesso à tecnologia e da transferência de tecnologia científica nacional e internacional sobre a gestão da biodiversidade brasileira.

16.3.1 Criar e apoiar programas que promovam a transferência e a difusão de tecnologias em gestão da biodiversidade.

16.3.2 Apoiar o intercâmbio de conhecimentos e tecnologias em temas selecionados e em áreas definidas como prioritárias para a gestão da biodiversidade, inclusive com centros de referência internacionais e estrangeiros.

16.3.3 Estabelecer mecanismos facilitadores do processo de intercâmbio e geração de conhecimento biotecnológico com seus potenciais usuários, resguardados os direitos sobre a propriedade intelectual.

16.3.4 Promover o aperfeiçoamento do arcabouço legal brasileiro no que diz respeito ao acesso à tecnologia e à transferência de tecnologias.

16.3.5 Estabelecer iniciativa nacional para disseminar o uso de tecnologias de domínio público úteis à gestão da biodiversidade.

16.3.6 Implantar unidades demonstrativas de utilização de tecnologias para conservação e utilização sustentável da biodiversidade.

16.3.7 Promover a cooperação para a certificação de tecnologias transferidas dos países desenvolvidos para o país.

16.3.8 Definir e implementar normas e procedimentos para o intercâmbio de tecnologias de utilização de recursos genéticos e biológicos, com transparência e assegurando os interesses nacionais, da comunidade acadêmica e dos povos indígenas, quilombolas e outras das comunidades locais.

## 16.4 Quarta diretriz: Mecanismos de financiamento. Integração, desenvolvimento e fortalecimento de mecanismos de financiamento da gestão da biodiversidade.

16.4.1 Fortalecer os fundos existentes de financiamento para a gestão da biodiversidade.

16.4.2 Estimular a criação de fundos de investimentos para a gestão da biodiversidade, incentivando inclusive a participação do setor empresarial.

16.4.3 Apoiar estudo para a criação de um fundo fiduciário ou outros mecanismos equivalentes, capazes de garantir a estabilidade financeira para implementação e manutenção de unidades de conservação, inclusive para regularização fundiária.

16.4.4 Estimular a criação de fundos ou outros mecanismos, geridos de forma participativa por povos indígenas, quilombolas e outras comunidades locais, que promovam a repartição justa e eqüitativa de benefícios, monetários ou não, decorrentes do acesso aos recursos genéticos, aos componentes do patrimônio genético e aos conhecimentos tradicionais associados.

16.4.5 Fortalecer a atuação em prol da biodiversidade dos órgãos estaduais de fomento à pesquisa em todos os estados.

16.4.6 Promover mecanismos que visem a assegurar a previsão e a aplicação de recursos orçamentários bem como de outras fontes para a gestão da biodiversidade.

16.4.7 Estimular a criação de linhas de financiamento por parte dos órgãos de fomento à pesquisa, direcionadas à implementação dos planos de pesquisa e à gestão da biodiversidade em unidades de conservação e em seu entorno.

16.4.8 Estimular a criação de linhas de financiamento para empreendimentos cooperativos e para pequenos e médios produtores rurais que usem os recursos da biodiversidade de forma sustentável.

16.4.9 Estimular a participação do setor privado em investimentos na gestão da biodiversidade do país.

16.4.10 Estimular a criação de mecanismos econômicos e fiscais que incentivem o setor empresarial a investir no inventário e na pesquisa sobre conservação e utilização sustentável da biodiversidade do país, em parceria com instituições de pesquisa e setor público.

16.4.11 Fomentar mediante incentivos econômicos, a conservação e a utilização sustentável da biodiversidade nas áreas sob domínio privado.

## 16.5 Quinta diretriz: Cooperação internacional. Promoção da cooperação internacional relativa à gestão da biodiversidade, com o fortalecimento de atos jurídicos internacionais.

16.5.1 Fortalecer a preparação e a participação de delegações brasileiras em negociações internacionais relacionadas aos temas da biodiversidade.

16.5.2 Promover a implementação de acordos e convenções internacionais relacionados com a gestão da biodiversidade, com atenção especial para a Convenção sobre Diversidade Biológica e seus programas e iniciativas.

16.5.3 Estabelecer sinergias visando à implementação das convenções ambientais assinadas pelo país.

16.5.4 Apoiar a negociação de acordos e convênios, justos e com benefícios para o país, para o intercâmbio de conhecimentos e transferências de tecnologia com centros de pesquisa internacionais e estrangeiros.

16.5.5 Fortalecer a cooperação internacional em pesquisas, programas e projetos relacionados com o conhecimento e com a gestão da biodiversidade, e agregação de valor aos seus componentes, em conformidade com as diretrizes do Componente 5.

16.5.6 Apoiar a participação dos centros de pesquisa nacionais em redes internacionais de pesquisa, desenvolvimento de tecnologias e programas relacionados ao conhecimento e à gestão da biodiversidade.

16.5.7 Identificar e estimular a utilização de mecanismos constantes de acordos internacionais que possam beneficiar a conservação e a utilização sustentável da biodiversidade, incluindo a utilização do Mecanismo de Desenvolvimento Limpo.

## 16.6 Sexta diretriz: Fortalecimento do marco-legal e integração de políticas setoriais. Promoção de ações visando ao fortalecimento da legislação brasileira sobre a biodiversidade e da articulação, da integração e da harmonização de políticas setoriais.

16.6.1 Promover o levantamento e a avaliação de todo o quadro normativo relativo à biodiversidade no Brasil, com vistas em propor a adequação para a gestão da biodiversidade.

16.6.2 Consolidar a legislação brasileira sobre a biodiversidade.

16.6.3 Promover a articulação, a integração e a harmonização de políticas setoriais relevantes para a conservação da biodiversidade, a utilização sustentável de seus componentes e a repartição de benefícios derivados da utilização de recursos genéticos, de componentes do patrimônio genético e de conhecimento tradicional associado.

::: {.callout-note icon=false appearance="simple"}

**ARCABOUÇO JURÍDICO INSTITUCIONAL**

:::

## 17.1 Muitas iniciativas institucionais em andamento no Brasil têm relação com os propósitos da Convenção sobre Diversidade Biológica - CDB e com as diretrizes e objetivos desta Política Nacional da Biodiversidade. Planos, políticas e programas setoriais necessitam de ser integrados, de forma a evitar-se a duplicação ou o conflito entre ações. A Política Nacional da Biodiversidade requer que mecanismos participativos sejam fortalecidos ou criados para que se articule a ação da sociedade em prol dos objetivos da CDB. A implementação desta política depende da atuação de diversos setores e ministérios do Governo Federal, segundo suas competências legais, bem como dos Governos Estaduais, do Distrito Federal, dos Governos Municipais e da sociedade civil.

## 17.2 Tendo em vista o conjunto de atores e políticas públicas que, direta ou indiretamente, guardam interesse com a gestão da biodiversidade e, portanto, com os compromissos assumidos pelo Brasil na implementação da CDB, é necessário que a implementação da Política propicie a criação ou o fortalecimento de arranjos institucionais que assegurem legitimidade e sustentabilidade no cumprimento dos objetivos da CDB, no que se refere à conservação e à utilização sustentável da biodiversidade e à repartição justa e eqüitativa dos benefícios decorrentes de sua utilização.

## 17.3 Na implementação da Política Nacional da Biodiversidade, caberá ao Ministério do Meio Ambiente: a) articular as ações da Política Nacional da Biodiversidade no âmbito do SISNAMA e junto aos demais setores do governo e da sociedade; b) acompanhar e avaliar a execução dos componentes da Política Nacional da Biodiversidade e elaborar relatórios nacionais sobre biodiversidade; c) monitorar, inclusive com indicadores, a execução das ações previstas na Política Nacional da Biodiversidade; d) formular e implementar programas e projetos em apoio à execução das ações previstas na Política Nacional da Biodiversidade e propor e negociar recursos financeiros; e) articular-se com os demais ministérios afetos aos temas tratados para a elaboração e encaminhamento de propostas de criação ou modificação de instrumentos legais necessários à boa execução da Política Nacional da Biodiversidade; f) promover a integração de políticas setoriais para aumentar a sinergia na implementação de ações direcionadas à gestão sustentável da biodiversidade (conservação, utilização sustentável e repartição de benefícios), evitando que estas sejam conflituosas; e g) estimular a cooperação interinstitucional e internacional para a melhoria da implementação das ações de gestão da biodiversidade.

## 17.4 A implementação da Política Nacional da Biodiversidade requer instância colegiada que busque o cumprimento dos interesses dessa Política Nacional da Biodiversidade junto ao governo federal, zele pela descentralização da execução das ações e vise assegurar a participação dos setores interessados.

## 17.5 Buscará, igualmente, essa instância colegiada cuidar para que os princípios e os objetivos da Política Nacional da Biodiversidade sejam cumpridos, prestando assistência técnica em apoio aos agentes públicos e privados responsáveis pela execução de seus componentes no território nacional.

## 17.6 O Ministério do Meio Ambiente, por intermédio do Programa Nacional da Diversidade Biológica - Pronabio, instituído pelo Decreto no 1.354, de 29 de dezembro de 1994, coordenará a implementação da Política Nacional da Biodiversidade, mediante a promoção da parceria entre o Poder Público e a sociedade civil para o conhecimento, a conservação da biodiversidade, a utilização sustentável de seus componentes e a repartição justa e eqüitativa dos benefícios derivados de sua utilização. *

