# Do Componente 5 - Acesso aos Recursos Genéticos e aos Conhecimentos Tradicionais Associados e Repartição de Benefícios.

::: {.callout-note icon=false appearance="simple"}

**Objetivo Geral: Permitir o acesso controlado aos recursos genéticos, aos componentes do patrimônio genético e aos conhecimentos tradicionais associados com vistas à agregação de valor mediante pesquisa científica e desenvolvimento tecnológico e de forma que a sociedade brasileira, em particular os povos indígenas, quilombolas e outras comunidades locais, possam compartilhar, justa e eqüitativamente, dos benefícios derivados do acesso aos recursos genéticos, aos componentes do patrimônio genético e aos conhecimentos tradicionais associados à biodiversidade.**

:::

## 14.1 Primeira diretriz: Acesso aos recursos genéticos e repartição de benefícios derivados da utilização dos recursos genéticos. Estabelecimento de um sistema controlado de acesso e de repartição justa e eqüitativa de benefícios oriundos da utilização de recursos genéticos e de componentes do patrimônio genético, que promova a agregação de valor mediante pesquisa científica e desenvolvimento tecnológico e que contribua para a conservação e para a utilização sustentável da biodiversidade.

14.1.1 Regulamentar e aplicar lei específica, e demais legislações necessárias, elaboradas com ampla participação da sociedade brasileira, em particular da comunidade acadêmica, do setor empresarial, dos povos indígenas, quilombolas e outras comunidades locais, para normalizar a relação entre provedor e usuário de recursos genéticos, de componentes do patrimônio genético e de conhecimentos tradicionais associados, e para estabelecer as bases legais para repartição justa e eqüitativa de benefícios derivados da utilização destes.

14.1.2 Estabelecer mecanismos legais e institucionais para maior publicidade e para viabilizar a participação da sociedade civil (organizações não-governamentais, povos indígenas, quilombolas e outras comunidades locais, setor acadêmico e setor privado) nos conselhos, comitês e órgãos colegiados que tratam do tema de gestão dos recursos genéticos e dos componentes do patrimônio genético.

14.1.3 Identificar as necessidades e os interesses de povos indígenas, quilombolas, outras comunidades locais, proprietários de terras, empresas tecnológicas nacionais e de agentes econômicos, órgãos governamentais, instituições de pesquisa e de desenvolvimento na regulamentação de sistema de acesso e de repartição justa e eqüitativa de benefícios oriundos da utilização de recursos genéticos e dos componentes do patrimônio genético.

14.1.4 Definir as normas e os procedimentos para a coleta, o armazenamento e para a remessa de recursos genéticos e de componentes do patrimônio genético para pesquisa e bioprospecção.

14.1.5 Implantar e aperfeiçoar mecanismos de acompanhamento, de controle social e de negociação governamental nos resultados da comercialização de produtos e processos oriundos da bioprospecção, associados à reversão de parte dos benefícios para fundos públicos destinados à pesquisa, à conservação e à utilização sustentável da biodiversidade.

14.1.6 Estabelecer contratos de exploração econômica da biodiversidade, cadastrados e homologados pelo governo federal, com cláusulas claras e objetivas, e com cláusulas de repartição de benefícios aos detentores dos recursos genéticos, dos componentes do patrimônio genético e dos conhecimentos tradicionais associados acessados.

14.1.7 Apoiar ações para implementação de infra-estrutura, de recursos humanos e recursos materiais em conselhos e órgãos colegiados que tratam da gestão de patrimônio genético, inclusive o Conselho de Gestão do Patrimônio Genético.

## 14.2 Segunda diretriz: Proteção de conhecimentos, inovações e práticas de povos indígenas, de quilombolas e de outras comunidades locais e repartição dos benefícios decorrentes do uso dos conhecimentos tradicionais associados à biodiversidade. Desenvolvimento de mecanismos que assegurem a proteção e a repartição justa e eqüitativa dos benefícios derivados do uso de conhecimentos, inovações e práticas de povos indígenas, quilombolas e outras comunidades locais, relevantes à conservação e à utilização sustentável da biodiversidade.

14.2.1 Estabelecer e implementar um regime legal sui generis de proteção a direitos intelectuais coletivos relativos à biodiversidade de povos indígenas, quilombolas e outras comunidades locais, com a ampla participação destas comunidades e povos.

14.2.2 Estabelecer e implementar instrumentos econômicos e regime jurídico específico que possibilitem a repartição justa e eqüitativa de benefícios derivados do acesso aos conhecimentos tradicionais associados, com a compensação econômica e de outros tipos para os detentores dos conhecimentos tradicionais associados à biodiversidade, segundo as demandas por estes definidas e resguardando seus valores culturais.

14.2.3 Estabelecer e implementar mecanismos para respeitar, preservar, resgatar, proteger a confidencialidade e manter o conhecimento, as inovações e as práticas de povos indígenas, quilombolas e outras comunidades locais.

14.2.4 Regulamentar e implementar mecanismos e instrumentos jurídicos que garantam aos povos indígenas, aos quilombolas e às outras comunidades locais a participação nos processos de negociação e definição de protocolos para acesso aos conhecimentos, inovações e práticas associados à biodiversidade e repartição dos benefícios derivados do seu uso.

14.2.5 Desenvolver e implementar mecanismos sui generis de proteção do conhecimento tradicional e de repartição justa e eqüitativa de benefícios para os povos indígenas, quilombolas, outras comunidades locais detentores de conhecimentos associados à biodiversidade, com a participação destes e resguardados seus interesses e valores.

14.2.6 Estabelecer iniciativas visando à gestão e ao controle participativos de povos indígenas, quilombolas e outras comunidades locais na identificação e no cadastramento, quando couber, de conhecimentos tradicionais, inovações e práticas associados à utilização dos componentes da biodiversidade.

14.2.7 Estabelecer, quando couber e com a participação direta dos detentores do conhecimento tradicional, mecanismo de cadastramento de conhecimentos tradicionais, inovações e práticas, associados à biodiversidade, de povos indígenas, quilombolas e outras comunidades locais, e de seu potencial para uso comercial, como uma das formas de prova quanto à origem destes conhecimentos.

14.2.8 Promover o reconhecimento e valorizar os direitos de povos indígenas, quilombolas e outras comunidades locais, quanto aos conhecimentos tradicionais associados à biodiversidade e da relação de mútua dependência entre diversidade etnocultural e biodiversidade.

14.2.9 Elaborar e implementar código de ética para trabalho com povos indígenas, quilombolas e outras comunidades locais, com a participação destes.

14.2.10 Assegurar o reconhecimento dos direitos intelectuais coletivos de povos indígenas, quilombolas e outras comunidades locais, e a necessária repartição de benefícios pelo uso de conhecimento tradicional associado à biodiversidade em seus territórios.

