# Do Componente 2 - Conservação da Biodiversidade

::: {.callout-note icon=false appearance="simple"}

**Objetivo Geral: Promover a conservação, in situ e ex situ, dos componentes da biodiversidade, incluindo variabilidade genética, de espécies e de ecossistemas, bem como dos serviços ambientais mantidos pela biodiversidade.**

:::

## 11.1 Primeira diretriz: Conservação de ecossistemas. Promoção de ações de conservação in situ da biodiversidade e dos ecossistemas em áreas não estabelecidas como unidades de conservação, mantendo os processos ecológicos e evolutivos e a oferta sustentável dos serviços ambientais.

11.1.1 Fortalecer a fiscalização para controle de atividades degradadoras e ilegais: desmatamento, destruição de habitats, caça, aprisionamento e comercialização de animais silvestres e coleta de plantas silvestres.

11.1.2 Desenvolver estudos e metodologias participativas que contribuam para a definição da abrangência e do uso de zonas de amortecimento para as unidades de conservação.

11.1.3 Planejar, promover, implantar e consolidar corredores ecológicos e outras formas de conectividade de paisagens, como forma de planejamento e gerenciamento regional da biodiversidade, incluindo compatibilização e integração das reservas legais, áreas de preservação permanentes e outras áreas protegidas.

11.1.4 Apoiar ações para elaboração dos zoneamentos ecológico-econômicos, de abrangência nacional, regional, estadual, municipal ou em bacias hidrográficas, com enfoque para o estabelecimento de unidades de conservação, e adotando suas conclusões, com diretrizes e roteiro metodológico mínimos comuns e com transparência, rigor científico e controle social.

11.1.5 Promover e apoiar estudos de melhoria dos sistemas de uso e de ocupação da terra, assegurando a conservação da biodiversidade e sua utilização sustentável, em áreas fora de unidades de conservação de proteção integral e inclusive em terras indígenas, quilombolas e de outras comunidades locais, com especial atenção às zonas de amortecimento de unidades de conservação.

11.1.6 Propor uma agenda de implementação de áreas e ações prioritárias para conservação da biodiversidade em cada estado e bioma brasileiro.

11.1.7 Promover e apoiar a conservação da biodiversidade no interior e no entorno de terras indígenas, de quilombolas e de outras comunidades locais, respeitando o uso etnoambiental do ecossistema pelos seus ocupantes.

11.1.8 Fortalecer mecanismos de incentivos para o setor privado e para comunidades locais com adoção de iniciativas voltadas à conservação da biodiversidade.

11.1.9 Criar mecanismos de incentivos à recuperação e à proteção de áreas de preservação permanente e de reservas legais previstas em Lei.

11.1.10 Criar estratégias para a conservação de ecossistemas pioneiros, garantindo sua representatividade e função.

11.1.11 Estabelecer uma iniciativa nacional para conservação e recuperação da biodiversidade de águas interiores, da zona costeira e da zona marinha.

11.1.12 Articular ações com o órgão responsável pelo controle sanitário e fitossanitário com vistas à troca de informações para impedir a entrada no país de espécies exóticas invasoras que possam afetar a biodiversidade.

11.1.13 Promover a prevenção, a erradicação e o controle de espécies exóticas invasoras que possam afetar a biodiversidade.

11.1.14 Promover ações de conservação visando a manutenção da estrutura e dos processos ecológicos e evolutivos e a oferta sustentável dos serviços ambientais.

11.1.15 Conservar a biodiversidade dos ecossistemas, inclusive naqueles sob sistemas intensivos de produção econômica, como seguro contra mudanças climáticas e alterações ambientais e econômicas imprevistas, preservando a capacidade dos componentes da biodiversidade se adaptarem a mudanças, inclusive as climáticas.

## 11.2 Segunda diretriz: Conservação de ecossistemas em unidades de conservação. Promoção de ações de conservação in situ da biodiversidade dos ecossistemas nas unidades de conservação, mantendo os processos ecológicos e evolutivos, a oferta sustentável dos serviços ambientais e a integridade dos ecossistemas.

11.2.1 Apoiar e promover a consolidação e a expansão do Sistema Nacional de Unidades de Conservação da Natureza - SNUC, com atenção particular para as unidades de proteção integral, garantindo a representatividade dos ecossistemas e das ecorregiões e a oferta sustentável dos serviços ambientais e a integridade dos ecossistemas.

11.2.2 Promover e apoiar o desenvolvimento de mecanismos técnicos e econômicos para a implementação efetiva de unidades de conservação.

11.2.3 Apoiar as ações do órgão oficial de controle fitossanitário com vistas a evitar a introdução de pragas e espécies exóticas invasoras em áreas no entorno e no interior de unidades de conservação.

11.2.4 Incentivar o estabelecimento de processos de gestão participativa, propiciando a tomada de decisões com participação da esfera federal, da estadual e da municipal do Poder Público e dos setores organizados da sociedade civil, em conformidade com a Lei do Sistema Nacional de Unidades de Conservação da Natureza - SNUC.

11.2.5 Incentivar a participação do setor privado na conservação in situ, com ênfase na criação de Reservas Particulares do Patrimônio Natural - RPPN, e no patrocínio de unidade de conservação pública.

11.2.6 Promover a criação de unidades de conservação de proteção integral e de uso sustentável, levando-se em consideração a representatividade, conectividade e complementaridade da unidade para o Sistema Nacional de Unidades de Conservação.

11.2.7 Desenvolver mecanismos adicionais de apoio às unidades de conservação de proteção integral e de uso sustentável, inclusive pela remuneração dos serviços ambientais prestados.

11.2.8 Promover o desenvolvimento e a implementação de um plano de ação para solucionar os conflitos devidos à sobreposição de unidades de conservação, terras indígenas e de quilombolas.

11.2.9 Incentivar e apoiar a criação de unidades de conservação marinhas com diversos graus de restrição e de exploração.

11.2.10 Conservar amostras representativas e suficientes da totalidade da biodiversidade, do patrimônio genético nacional (inclusive de espécies domesticadas), da diversidade de ecossistemas e da flora e fauna brasileira (inclusive de espécies ameaçadas), como reserva estratégica para usufruto futuro.

## 11.3 Terceira diretriz: Conservação in situ de espécies. Consolidação de ações de conservação in situ das espécies que compõem a biodiversidade, com o objetivo de reduzir a erosão genética, de promover sua conservação e utilização sustentável, particularmente das espécies ameaçadas, bem como dos processos ecológicos e evolutivos a elas associados e de manter os serviços ambientais.

11.3.1 Criar, identificar e estabelecer iniciativas, programas e projetos de conservação e recuperação de espécies ameaçadas, endêmicas ou insuficientemente conhecidas.

11.3.2 Identificar áreas para criação de novas unidades de conservação, baseando-se nas necessidades das espécies ameaçadas.

11.3.3 Fortalecer e disseminar mecanismos de incentivo para empresas privadas e comunidades que desenvolvem projetos de conservação de espécies ameaçadas.

11.3.4 Implementar e aperfeiçoar o sistema de autorização, vigilância e acompanhamento de coleta de material biológico e de componentes do patrimônio genético.

11.3.5 Promover a regulamentação e a implementação de reservas genéticas para proteger variedades locais de espécies silvestres usadas no extrativismo, na agricultura e na aqüicultura.

11.3.6 Implementar ações para maior proteção de espécies ameaçadas dentro e fora de unidades de conservação.

11.3.7 Promover e aperfeiçoar as ações de manejo de espécies-problema em situação de descontrole populacional.

11.3.8 Estabelecer mecanismos para tornar obrigatória a inclusão, em parte ou no todo, de ambientes especiais que apresentam alto grau de endemismo ou contenham espécies ameaçadas nas Zonas Intangíveis das Unidades de Conservação de Uso Sustentável.

11.3.9 Estabelecer medidas de proteção das espécies ameaçadas nas terras indígenas e nas terras de quilombolas.

## 11.4 Quarta diretriz: Conservação ex situ de espécies. Consolidação de ações de conservação ex situ de espécies e de sua variabilidade genética, com ênfase nas espécies ameaçadas e nas espécies com potencial de uso econômico, em conformidade com os objetivos específicos estabelecidos nas diretrizes do Componente 5.

11.4.1 Desenvolver estudos para a conservação ex situ de espécies, com ênfase nas espécies ameaçadas e nas espécies com potencial de uso econômico.

11.4.2 Desenvolver, promover e apoiar estudos e estabelecer metodologias para conservação e manutenção dos bancos de germoplasma das espécies nativas e exóticas de interesse científico e comercial.

11.4.3 Promover a manutenção, a caracterização e a documentação do germoplasma de plantas, animais, fungos e microrganismos contido nas instituições científicas e nos centros nacionais e regionais, de maneira a estabelecer coleções nucleares para fomentar programas de melhoramento genético.

11.4.4 Integrar iniciativas, planos e programas de conservação ex situ de espécies, com ênfase nas espécies ameaçadas e nas espécies com potencial de uso econômico.

11.4.5 Promover a conservação ex situ visando à obtenção de matrizes animais e vegetais, inclusive microrganismos, de espécies ameaçadas ou com potencial de uso econômico para formação de coleções vivas representativas.

11.4.6 Ampliar, fortalecer e integrar o sistema de herbários, museus zoológicos, coleções etnobotânicas, criadouros de vida silvestre, jardins botânicos, arboretos, hortos florestais, coleções zoológicas, coleções botânicas, viveiros de plantas nativas, coleções de cultura de microrganismos, bancos de germoplasma vegetal, núcleos de criação animal, zoológicos, aquários e oceanários.

11.4.7 Integrar jardins botânicos, zoológicos e criadouros de vida silvestre aos planos nacionais de conservação de recursos genéticos animais e vegetais e de pesquisa ambiental, especialmente em áreas de alto endemismo.

11.4.8 Criar e fortalecer centros de triagem de animais e plantas silvestres, integrando-os ao sistema de zoológicos e jardins botânicos, para serem transformados em centros de conservação de fauna e de flora.

11.4.9 Criar centros e promover iniciativas para a reprodução de espécies ameaçadas, utilizando técnicas como inseminação artificial, fertilização in vitro, entre outras.

11.4.10 Incentivar a participação do setor privado na estratégia de conservação ex situ da biodiversidade.

11.4.11 Promover medidas e iniciativas para o enriquecimento da variabilidade genética disponível nos bancos de germoplasma, estabelecendo coleções representativas do patrimônio genético (animal, vegetal e de microrganismos).

11.4.12 Estabelecer e apoiar iniciativas de coleta para aumentar a representatividade geográfica dos bancos de germoplasma.

11.4.13 Criar e manter bancos de germoplasma regionais e coleções de base para a conservação da variabilidade genética, promovendo principalmente a conservação de espécies nativas sub-representadas em coleções, variedades locais, parentes silvestres, espécies raras, endêmicas, ameaçadas ou com potencial econômico.

11.4.14 Estabelecer iniciativas de coleta, reintrodução e intercâmbio de espécies nativas de importância socioeconômica, incluindo variedades locais de espécies domesticadas e de espécies ameaçadas, para manutenção de sua variabilidade genética.

11.4.15 Apoiar e subsidiar a conservação e a ampliação de bancos de germoplasma de espécies introduzidas, com fins econômicos ou ornamentais, mantidas por entidades de pesquisa, jardins botânicos, zoológicos e pela iniciativa privada.

11.4.16 Ampliar os programas nacionais de coleta e conservação de microrganismos do solo de interesse econômico.

11.4.17 Integrar as ações de conservação ex situ com as ações de gestão do acesso a recursos genéticos e repartição de benefícios derivados da utilização do conhecimento tradicional.

11.4.18 Apoiar as ações de órgão oficial de controle sanitário e fitossanitário no que diz respeito ao controle de espécies invasoras ou pragas.

## 11.5 Quinta diretriz: Instrumentos econômicos e tecnológicos de conservação da biodiversidade. Desenvolvimento de instrumentos econômicos e tecnológicos para a conservação da biodiversidade.

11.5.1 Promover estudos para a avaliação da efetividade dos instrumentos econômicos para a conservação da biodiversidade.

11.5.2 Criar e consolidar legislação específica relativa ao uso de instrumentos econômicos que visem ao estímulo à conservação da biodiversidade, associado ao processo de reforma tributária.

11.5.3 Desenvolver instrumentos econômicos e legais para reduzir as pressões antrópicas sobre a biodiversidade, associado ao processo de reforma tributária.

11.5.4 Desenvolver instrumentos econômicos e instrumentos legais para cobrança pública, quando couber, pelo uso de serviços ambientais, associado ao processo de reforma tributária.

11.5.5 Promover a internalização de custos e benefícios da conservação da biodiversidade (bens e serviços) na contabilidade pública e privada.

11.5.6 Estimular mecanismos para reversão dos benefícios da cobrança pública pelo uso de serviços ambientais da biodiversidade para a sua conservação.

11.5.7 Criar e implantar mecanismos tributários, creditícios e de facilitação administrativa específicos para proprietários rurais que mantêm reservas legais e áreas de preservação permanente protegidas.

11.5.8 Aprimorar os instrumentos legais existentes de estímulo à conservação da biodiversidade por meio do imposto sobre circulação de mercadoria (ICMS Ecológico) e incentivar sua adoção em todos os estados da federação, incentivando a aplicação dos recursos na gestão da biodiversidade.

