# Do Componente 3 - Utilização Sustentável dos Componentes da Biodiversidade

::: {.callout-note icon=false appearance="simple"}

**Objetivo Geral: Promover mecanismos e instrumentos que envolvam todos os setores governamentais e não-governamentais, públicos e privados, que atuam na utilização de componentes da biodiversidade, visando que toda utilização de componentes da biodiversidade seja sustentável e considerando não apenas seu valor econômico, mas também os valores ambientais, sociais e culturais da biodiversidade.**

:::

## 12.1 Primeira diretriz: Gestão da biotecnologia e da biossegurança. Elaboração e implementação de instrumentos e mecanismos jurídicos e econômicos que incentivem o desenvolvimento de um setor nacional de biotecnologia competitivo e de excelência, com biossegurança e com atenção para as oportunidades de utilização sustentável de componentes do patrimônio genético, em conformidade com a legislação vigente e com as diretrizes e objetivos específicos estabelecidos no Componente 5.

12.1.1 Elaborar e implementar códigos de ética para a biotecnologia e a bioprospecção, de forma participativa, envolvendo os diferentes segmentos da sociedade brasileira, com base na legislação vigente.

12.1.2 Consolidar a regulamentação dos usos de produtos geneticamente modificados, com base na legislação vigente, em conformidade com o princípio da precaução e com análise de risco dos potenciais impactos sobre a biodiversidade, a saúde e o meio ambiente, envolvendo os diferentes segmentos da sociedade brasileira, garantindo a transparência e o controle social destes e com a responsabilização civil, criminal e administrativa para introdução ou difusão não autorizada de organismos geneticamente modificados que ofereçam riscos ao meio ambiente e à saúde humana.

12.1.3 Consolidar a estruturação, tanto na composição quanto os procedimentos de operação, dos órgãos colegiados que tratam da utilização da biodiversidade, especialmente a Comissão Técnica Nacional de Biossegurança - CTNBio e o Conselho de Gestão do Patrimônio Genético - CGEN.

12.1.4 Fomentar a criação e o fortalecimento de instituições nacionais e de grupos de pesquisa nacionais, públicos e privados, especializados em bioprospecção, biotecnologia e biossegurança, inclusive apoiando estudos e projetos para a melhoria dos conhecimentos sobre a biossegurança e avaliação de conformidade de organismos geneticamente modificados e produtos derivados.

12.1.6 Apoiar e fomentar a formação de empresas nacionais dedicadas à pesquisa científica e tecnológica, à agregação de valor, à conservação e à utilização sustentável dos recursos biológicos e genéticos.

12.1.7 Apoiar e fomentar a formação de parcerias entre instituições científicas públicas e privadas, inclusive empresas nacionais de tecnologia, com suas congêneres estrangeiras, objetivando estabelecer e consolidar as cadeias de agregação de valor, comercialização e retorno de benefícios relativos a negócios da biodiversidade.

12.1.8 Apoiar e fomentar a formação de pessoal pós-graduado especializado em administração de negócios sustentáveis com biodiversidade, com o objetivo de seu aproveitamento pelos sistemas públicos e privados ativos no setor, conferindo ao país condições adequadas de interlocução com seus parceiros estrangeiros.

12.1.9 Exigir licenciamento ambiental de atividades e empreendimentos que façam uso de Organismos Geneticamente Modificados - OGM e derivados, efetiva ou potencialmente poluidores, nos termos da legislação vigente.

12.1.10 Apoiar a implementação da infra-estrutura e capacitação de recursos humanos dos órgãos públicos e instituições privadas para avaliação de conformidade de material biológico, certificação e rotulagem de produtos, licenciamento ambiental e estudo de impacto ambiental.

## 12.2 Segunda diretriz: Gestão da utilização sustentável dos recursos biológicos. Estruturação de sistemas reguladores da utilização dos recursos da biodiversidade.

12.2.1 Criar e consolidar programas de manejo e regulamentação de atividades relacionadas à utilização sustentável da biodiversidade.

12.2.2 Promover o ordenamento e a gestão territorial das áreas de exploração dos recursos ambientais, de acordo com a capacidade de suporte destes e de forma integrada com os esforços de conservação in situ da biodiversidade.

12.2.3 Implementar ações que atendam às demandas de povos indígenas, de quilombolas e de outras comunidades locais, quanto às prioridades relacionadas à conservação e à utilização sustentável dos recursos biológicos existentes em seus territórios, salvaguardando os princípios e a legislação inerentes à matéria e assegurando a sua sustentabilidade nos seus locais de origem.

12.2.4 Desenvolver e apoiar programas, ações e medidas que promovam a conservação e a utilização sustentável da agrobiodiversidade.

12.2.5 Promover políticas e programas visando à agregação de valor e à utilização sustentável dos recursos biológicos.

12.2.6 Promover programas de apoio a pequenas e médias empresas, que utilizem recursos da biodiversidade de forma sustentável.

12.2.7 Promover instrumentos para assegurar que atividades turísticas sejam compatíveis com a conservação e a utilização sustentável da biodiversidade.

12.2.8 Promover, de forma integrada, e quando legalmente permitido, a utilização sustentável de recursos florestais, madeireiros e não-madeireiros, pesqueiros e faunísticos, privilegiando o manejo certificado, a reposição, o uso múltiplo e a manutenção dos estoques.

12.2.9 Adaptar para as condições brasileiras e aplicar os princípios da Abordagem Ecossistêmica no manejo da biodiversidade.

## 12.3 Terceira diretriz: Instrumentos econômicos, tecnológicos e incentivo às práticas e aos negócios sustentáveis para a utilização da biodiversidade. Implantação de mecanismos, inclusive fiscais e financeiros, para incentivar empreendimentos e iniciativas produtivas de utilização sustentável da biodiversidade.

12.3.1 Criar e consolidar legislação específica, relativa ao uso de instrumentos econômicos que visem ao estímulo à utilização sustentável da biodiversidade.

12.3.2 Criar e fortalecer mecanismos de incentivos fiscais e de crédito, para criação e aplicação de tecnologias, empreendimentos e programas relacionados com a utilização sustentável da biodiversidade.

12.3.3 Promover incentivos econômicos para o desenvolvimento e a consolidação de práticas e negócios realizados em unidades de conservação de proteção integral e de uso sustentável, em territórios quilombolas, terras indígenas e demais espaços territoriais sob proteção formal do Poder Público.

12.3.4 Promover a internalização de custos e benefícios da utilização da biodiversidade (bens e serviços) na contabilidade pública e privada.

12.3.5 Identificar, avaliar e promover experiências, práticas, tecnologias, negócios e mercados para produtos oriundos da utilização sustentável da biodiversidade, incentivando a certificação voluntária de processos e produtos, de forma participativa e integrada.

12.3.6 Estimular o uso de instrumentos voluntários de certificação de produtos, processos, empresas, órgãos do governo e outras formas de organizações produtivas relacionadas com a utilização sustentável da biodiversidade, inclusive nas compras do governo.

12.3.7 Promover a inserção de espécies nativas com valor comercial no mercado interno e externo, bem como a diversificação da utilização sustentável destas espécies.

12.3.8 Estimular a interação e a articulação dos agentes da Política Nacional da Biodiversidade com o setor empresarial para identificar oportunidades de negócios com a utilização sustentável dos componentes da biodiversidade.

12.3.9 Apoiar as comunidades locais na identificação e no desenvolvimento de práticas e negócios sustentáveis.

12.3.10 Apoiar, de forma integrada, a domesticação e a utilização sustentável de espécies nativas da flora, da fauna e dos microrganismos com potencial econômico.

12.3.11 Estimular a implantação de criadouros de animais silvestres e viveiros de plantas nativas para consumo e comercialização.

12.3.12 Estimular a utilização sustentável de produtos não madeireiros e as atividades de extrativismo sustentável, com agregação de valor local por intermédio de protocolos para produção e comercialização destes produtos.

12.3.13 Estimular a implantação de projetos baseados no Mecanismo de Desenvolvimento Limpo do Protocolo de Quioto que estejam de acordo com a conservação e utilização sustentável da biodiversidade.

12.3.14 Incentivar políticas de apoio a novas empresas, visando à agregação de valor, à conservação, à utilização sustentável dos recursos biológicos e genéticos.

## 12.4 Quarta diretriz: Utilização da biodiversidade nas unidades de conservação de uso sustentável. Desenvolvimento de métodos para a utilização sustentável da biodiversidade e indicadores para medir sua efetividade nas unidades de conservação de uso sustentável.

12.4.1 Aprimorar métodos e criar novas tecnologias para a utilização de recursos biológicos, eliminando ou minimizando os impactos causados à biodiversidade.

12.4.2 Desenvolver estudos de sustentabilidade ambiental, econômica, social e cultural da utilização dos recursos biológicos.

12.4.3 Fomentar o desenvolvimento de projetos de utilização sustentável de recursos biológicos oriundos de associações e comunidades em unidades de conservação de uso sustentável, de forma a integrar com a conservação da biodiversidade.

12.4.4 Estabelecer critérios para que os planos de manejo de exploração de qualquer recurso biológico incluam o monitoramento dos processos de recuperação destes recursos.

