# Do Componente 6 - Educação, Sensibilização Pública, Informação e Divulgação sobre Biodiversidade.

::: {.callout-note icon=false appearance="simple"}

**Objetivo Geral: Sistematizar, integrar e difundir informações sobre a biodiversidade, seu potencial para desenvolvimento e a necessidade de sua conservação e de sua utilização sustentável, bem como da repartição dos benefícios derivados da utilização de recursos genéticos, de componentes do patrimônio genético e do conhecimento tradicional associado, nos diversos níveis de educação, bem como junto à população e aos tomadores de decisão.**

:::

## 15.1 Primeira diretriz: Sistemas de informação e divulgação. Desenvolvimento de sistema nacional de informação e divulgação de informações sobre biodiversidade.

15.1.1 Difundir informações para todos os setores da sociedade sobre biodiversidade brasileira.

15.1.2 Facilitar o acesso à informação e promover a divulgação da informação para a tomada de decisões por parte dos diferentes produtores e usuários de bens e serviços advindos da biodiversidade.

15.1.3 Instituir e manter permanentemente atualizada uma rede de informação sobre gestão da biodiversidade, promovendo e facilitando o acesso a uma base de dados disponível em meio eletrônico, integrando-a com iniciativas já existentes.

15.1.4 Identificar e catalogar as coleções biológicas (herbários, coleções zoológicas, de microrganismos e de germoplasma) existentes no país, seguida de padronização e integração das informações sobre as mesmas.

15.1.5 Mapear e manter bancos de dados sobre variedade locais, parentes silvestres das plantas nacionais cultivadas e de cultivares de uso atual ou potencial.

15.1.6 Instituir e implementar mecanismos para facilitar o acesso às informações sobre coleções de componentes da biodiversidade brasileira existentes no exterior e, quando couber, a repatriação do material associado à informação.

15.1.7 Apoiar e divulgar experiências de conservação e utilização sustentável da biodiversidade, inclusive por povos indígenas, quilombolas e outras comunidades locais, quando houver consentimento destes e desde que sejam resguardados os direitos sobre a propriedade intelectual e o interesse nacional.

15.1.8 Divulgar os instrumentos econômicos, financeiros e jurídicos voltados para a gestão da biodiversidade.

15.1.9 Organizar, promover a produção, distribuir e facilitar o acesso a materiais institucionais e educativos sobre biodiversidade e sobre aspectos étnicos e culturais relacionados à biodiversidade.

15.1.10 Promover a elaboração e a sistematização de estudos de casos e lições aprendidas quanto à gestão sustentável da biodiversidade.

15.1.11 Criar mecanismos de monitoramento da utilização de dados, do acesso às redes de bancos de dados e dos usuários dessas redes, visando à repartição dos benefícios oriundos do uso das informações disponíveis na rede.

15.1.12 Promover e apoiar programas nacionais de publicações científicas sobre temas referentes à biodiversidade, e incentivar a valorização das publicações nacionais relativas à diversidade biológica das instituições ligadas à pesquisa e ao ensino.

## 15.2 Segunda diretriz: Sensibilização pública. Realização de programas e campanhas de sensibilização sobre a biodiversidade.

15.2.1 Promover e apoiar campanhas nacionais, regionais e locais para valorização e difusão de conhecimentos sobre a biodiversidade, ressaltando a importância e o valor da heterogeneidade dos diferentes biomas para a conservação e para a utilização sustentável da biodiversidade.

15.2.2 Promover campanhas nacionais de valorização da diversidade cultural e dos conhecimentos tradicionais sobre a biodiversidade.

15.2.3 Promover campanhas junto aos setores produtivos, especialmente os setores agropecuário, pesqueiro e de exploração mineral, e ao de pesquisas sobre a importância das reservas legais e áreas de preservação permanentes no processo de conservação da biodiversidade.

15.2.4 Criar novos estímulos, tais como prêmios e concursos, que promovam o envolvimento das populações na defesa das espécies ameaçadas e dos biomas submetidos a pressão antrópica, levando-se em consideração as especificidades regionais.

15.2.5 Promover e apoiar a sensibilização e a capacitação de tomadores de decisão, formadores de opinião e do setor empresarial quanto à importância da biodiversidade.

15.2.6 Estimular a atuação da sociedade civil organizada para a condução de iniciativas em educação ambiental relacionadas à biodiversidade.

15.2.7 Divulgar informações sobre conhecimentos tradicionais, inovações e práticas de povos indígenas, quilombolas e outras de comunidades locais e sua importância na conservação da biodiversidade, quando houver consentimento destes.

15.2.8 Sensibilizar povos indígenas, quilombolas e outras comunidades locais sobre a importância do conhecimento que detêm sobre a biodiversidade, possibilitando ações de conservação, de utilização sustentável da biodiversidade e de repartição dos benefícios decorrentes do uso dos conhecimentos tradicionais associados à biodiversidade.

15.2.9 Divulgar a importância da interação entre a gestão da biodiversidade e a saúde pública.

15.2.10 Promover sensibilização para a gestão da biodiversidade em áreas de uso público.

15.2.11 Desenvolver, implementar e divulgar indicadores que permitam avaliar e acompanhar a evolução do grau de sensibilização da sociedade quanto à biodiversidade.

15.2.12 Promover a integração das ações de fiscalização do meio ambiente com programas de educação ambiental, no que se refere à biodiversidade.

15.2.13 Promover cursos e treinamentos para jornalistas sobre conceitos de gestão da biodiversidade.

## 15.3 Terceira diretriz: Incorporação de temas relativos à conservação e à utilização sustentável da biodiversidade na educação. Integração de temas relativos à gestão da biodiversidade nos processos de educação.

15.3.1 Fortalecer o uso do tema biodiversidade como conteúdo do tema transversal meio ambiente proposto por parâmetros e diretrizes curriculares nas políticas de formação continuada de professores.

15.3.2 Promover articulação entre os órgãos ambientais e as instituições educacionais, para atualização contínua das informações sobre a biodiversidade.

15.3.3 Introduzir o tema "biodiversidade" nas atividades de extensão comunitária.

15.3.4 Incorporar na educação formal os princípios da Convenção sobre Diversidade Biológica e da etnobiodiversidade, atendendo ao princípio da educação diferenciada para povos indígenas, quilombolas e outras comunidades locais.

15.3.5 Estimular parcerias, pesquisas e demais atividades entre universidades, organizações não-governamentais, órgãos profissionais e iniciativa privada para o aprimoramento contínuo dos profissionais de educação.

15.3.6 Promover a formação inicial e continuada dos profissionais de educação ambiental, no que se refere à biodiversidade.

15.3.7 Promover a capacitação dos técnicos de extensão rural e dos agentes de saúde sobre o tema "biodiversidade".

15.3.8 Promover iniciativas para articulação das instituições envolvidas com educação ambiental (instituições de ensino, de pesquisa, de conservação e da sociedade civil) em uma rede de centros de educação ambiental, para tratar do tema "biodiversidade".

15.3.9 Estabelecer a integração entre os ministérios e os demais órgãos de governo para a articulação das políticas educacionais de gestão da biodiversidade.

15.3.10 Fortalecer a Política Nacional de Educação Ambiental.

